### ISSUE TITLE
Preprocessing.py

### ISSUE THREAD

**Issue by nasatony** [illidanlab/urgent-care-comparative#1]
Lack of documentation and corresponding README file is incorrect.

None of the defined functions are called from main(), labels are not saved.

filename_dx, filename_admits, filename_pts,filename_ddx,filename_icustays are not defined or
described. Even after figuring out how to generate these files, additional errors prevent progress.

**Comment by jiayuzhou** [comment]
We are sorry that you experience difficulties when running the code. We will complete the information soon. @af1tang Please follow up on this and make suggested changes.

**Comment by nasatony** [comment]
謝謝


________________________________
