### ISSUE TITLE
DataFrame object format

### ISSUE THREAD

**Issue by nasatony** [illidanlab/urgent-care-comparative#2]
Ubuntu 16.04 / Python 3.6 (Anaconda) / Pandas 0.22.0
$ python preprocess.py --path_tables ../local_mimic/tables --path_views ../local_mimic/views --path_save ../local_mimic/save
Traceback (most recent call last):
  File "preprocess.py", line 401, in <module>
    labels = make_labels()
  File "preprocess.py", line 37, in make_labels
    icu_details = icu_details[(icu_details.age>=18)&(icu_details.los_hospital>=1)&(icu_details.los_icu>=1)]
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'age'

Two problems:
(1) icustay-detail.sql generates 'admission_age' rather than 'age' header column
(2) preprocess.make_labels(): read_csv needs a defined separator, e.g.
icu_details = pd.read_csv(path_views + '/icustay_detail.csv', sep = '|', header = 'infer')

icustay_detail.csv - Header + First 4 lines ('admission_age' changed to 'age'):
subject_id | hadm_id | icustay_id | gender |         dod         |      admittime      |      dischtime      | los_hospital | age |                        ethnicity                         | admission_type | hospital_expire_flag | hospstay_seq | first_hosp_stay |       intime        |       outtime       | los_icu  | icustay_seq | first_icu_stay
------------+---------+------------+--------+---------------------+---------------------+---------------------+--------------+---------------+----------------------------------------------------------+----------------+----------------------+--------------+-----------------+---------------------+---------------------+----------+-------------+----------------
          2 |  163353 |     243653 | M      |                     | 2138-07-17 19:04:00 | 2138-07-21 15:48:00 |       3.8639 |        0.0022 | ASIAN                                                    | NEWBORN        |                    0 |            1 | t               | 2138-07-17 21:20:07 | 2138-07-17 23:32:21 |   0.0918 |           1 | t
          3 |  145834 |     211552 | M      | 2102-06-14 00:00:00 | 2101-10-20 19:08:00 | 2101-10-31 13:58:00 |      10.7847 |       76.5268 | WHITE                                                    | EMERGENCY      |                    0 |            1 | t               | 2101-10-20 19:10:11 | 2101-10-26 20:43:09 |   6.0646 |           1 | t
          4 |  185777 |     294638 | F      |                     | 2191-03-16 00:28:00 | 2191-03-23 18:41:00 |       7.7590 |       47.8450 | WHITE                                                    | EMERGENCY      |                    0 |            1 | t               | 2191-03-16 00:29:31 | 2191-03-17 16:46:31 |   1.6785 |           1 | t
          5 |  178980 |     214757 | M      |                     | 2103-02-02 04:31:00 | 2103-02-04 12:15:00 |       2.3222 |        0.0005 | ASIAN                                                    | NEWBORN        |                    0 |            1 | t               | 2103-02-02 06:04:24 | 2103-02-02 08:06:00 |   0.0844 |           1 | t

**Comment by nasatony** [comment]
Resolved issues by changing format of captured materialized view file:

subject_id,hadm_id,icustay_id,gender,dod,admittime,dischtime,los_hospital,age,ethnicity,admission_type,hospital_expire_flag,hospstay_seq,first_hosp_stay,intime,outtime,los_icu,icustay_seq,first_icu_stay
2,163353,243653,M,,2138-07-17 19:04:00,2138-07-21 15:48:00,3.8639,0.0022,ASIAN,NEWBORN,0,1,t,2138-07-17 21:20:07,2138-07-17 23:32:21,0.0918,1,t
3,145834,211552,M,2102-06-14 00:00:00,2101-10-20 19:08:00,2101-10-31 13:58:00,10.7847,76.5268,WHITE,EMERGENCY,0,1,t,2101-10-20 19:10:11,2101-10-26 20:43:09,6.0646,1,t
4,185777,294638,F,,2191-03-16 00:28:00,2191-03-23 18:41:00,7.7590,47.8450,WHITE,EMERGENCY,0,1,t,2191-03-16 00:29:31,2191-03-17 16:46:31,1.6785,1,t
5,178980,214757,M,,2103-02-02 04:31:00,2103-02-04 12:15:00,2.3222,0.0005,ASIAN,NEWBORN,0,1,t,2103-02-02 06:04:24,2103-02-02 08:06:00,0.0844,1,t

**Comment by nasatony** [comment]
Note: It was still necessary to change names -- 'admission_age' -> 'age'.

Another error occurs now:

$ ~/Research/ucc_2019$ python preprocess.py --path_tables ../local_mimic/tables --path_views ../local_mimic/views --path_save ../local_mimic/save
================================================================================
                      Making pivot table for ICD-9 codes.                       
================================================================================
N/A% (0 of 33366) |                                                                            | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "preprocess.py", line 401, in <module>
    labels = make_labels()
  File "preprocess.py", line 43, in make_labels
    dx_dct, dx_freq = pivot_icd(subj)
  File "preprocess.py", line 106, in pivot_icd
    dictionary = df[(df.subject_id == s)][['hadm_id', 'icd9_code']].groupby('hadm_id')['icd9_code'].apply(list).to_dict()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'subject_id'

**Comment by nasatony** [comment]
Resolved issue with following modification:
local_mimic/tables/diagnoses_icd.csv
"ROW_ID","SUBJECT_ID","HADM_ID","SEQ_NUM","ICD9_CODE"
changed to
"row_id","subject_id","hadm_id","seq_num","icd9_code"

**Comment by nasatony** [comment]
Similarly,
local_mimic/tables/d_icd_diagnoses.csv
"ROW_ID","ICD9_CODE","SHORT_TITLE","LONG_TITLE"
changed to
"row_id","icd9_code","short_title","long_title"

**Comment by af1tang** [comment]
@nasatony  Thanks for the feedback. Will update these in the documentation for setting up the pivot tables from MIMIC.

**Comment by af1tang** [comment]
These changes are added to the documentation.
