### ISSUE TITLE
Checkpoint directory results

### ISSUE THREAD

**Issue by nasatony** [illidanlab/urgent-care-comparative#4]
How does one view the raw stats file in the checkpoint directory, e.g.

$ more save/checkpoint/lstm-dx-x19-w2v/scores/raw_stats

?}q
scalar
qcnumpy
dtype
qX
b??kV???q
Kh???R/???q?qRqKh4F????q?qRqKh?g?I????q?qRqKh?T??Qw??q?qRqKhfr??????q?qqKhK?wl????q?qRqKh?Y?t????q ?q!Rq"h???=???q#?q$Rq%K	-h??%;'???q&?q'Rq(K
h??r	???q)?q*Rq+K

**Comment by jiayuzhou** [comment]
This should be some Python serialized object that you should be read into Python data structures.

**Comment by nasatony** [comment]
非常感谢你
周家峪
