### ISSUE TITLE
main.py -- differential diagnosis

### ISSUE THREAD

**Issue by nasatony** [illidanlab/urgent-care-comparative#5]
The main.py program does not appear to save the differential diagnosis pathology names
and it is not obvious how to obtain them. Although the scores for the top 25 diagnoses are
saved, the corresponding label names aren't provided. 

How, does one obtain the DDX label names ?

Thanks in advance !!

**Comment by nasatony** [comment]
Just to clarify -- I would like to access the label name mapping for each of the 25 diagnoses associated with the computed statistics below ...

================================================================================
                                      Opts                                      
--------------------------------------------------------------------------------
               checkpoint_path: ../local_mimic/save/checkpoint/lstm-dx-x19-w2v/ 
================================================================================
1 -fold
tr_auc : {0: 0.9989425760146542, 1: 0.9986797923754585, 2: 0.997927591715439, 3: 0.998843330128917, 4: 0.9833153937894555, 5
: 0.9969000779052066, 6: 0.9936225050470652, 7: 0.9929969097673175, 8: 0.9956349022323205, 9: 0.9909855036951439, 10: 0.9882
857540913099, 11: 0.9655706759229371, 12: 0.9912724563412425, 13: 0.959900095009026, 14: 0.9987854584552618, 15: 0.982448640
0153486, 16: 0.981914370519212, 17: 0.9964624525085396, 18: 0.9876295847388693, 19: 0.9929759799463393, 20: 0.99341199533127
77, 21: 0.9978552717514934, 22: 0.9798664736553245, 23: 0.9926250324008696, 24: 0.9850495227278939, 'micro': 0.9605273790972
948}

f1_score : {0: 0.9863074204946997, 1: 0.976508854354897, 2: 0.9730754645430413, 3: 0.9839096199931531, 4: 0.8351409978308026
, 5: 0.9727536231884059, 6: 0.7960741548527809, 7: 0.9051546391752578, 8: 0.9172831203765972, 9: 0.8635043562439496, 10: 0.9
251000571755289, 11: 0.7035256410256411, 12: 0.8039492242595205, 13: 0.6180904522613065, 14: 0.919760479041916, 15: 0.739852
3985239852, 16: 0.7730941704035874, 17: 0.8324324324324324, 18: 0.7915611814345991, 19: 0.7591111111111111, 20: 0.6499102333
931777, 21: 0.6492753623188406, 22: 0.6575342465753424, 23: 0.7750362844702469, 24: 0.8275109170305677, 'micro': 0.875707136
640557}

te_auc : {0: 0.9991360592773869, 1: 0.9981627036918534, 2: 0.9992154412580171, 3: 0.9995720601706862, 4: 0.9866137586256796,
 5: 0.9985816943551336, 6: 0.993415832260415, 7: 0.994692677276947, 8: 0.9954648627155906, 9: 0.9937643079968677, 10: 0.9961
590269910781, 11: 0.9697424081580132, 12: 0.992698058419684, 13: 0.9716063867282743, 14: 0.9982966480773221, 15: 0.990596555
5010008, 16: 0.9865152094674722, 17: 0.9960569518385539, 18: 0.9925029782857012, 19: 0.9924305244031193, 20: 0.9920836376553
04, 21: 0.9985501598457026, 22: 0.991983455536755, 23: 0.9947694318643613, 24: 0.9914808405782425, 'micro': 0.97058623753147
38}

sen : {0: 0.9924444444444445, 1: 0.9818313953488372, 2: 0.9922660479505027, 3: 0.9958419958419958, 4: 0.958904109589041, 5: 
0.9778554778554779, 6: 0.9656084656084656, 7: 0.9854096520763187, 8: 0.9770773638968482, 9: 0.9674620390455532, 10: 0.971188
4753901561, 11: 0.8868686868686869, 12: 0.9726962457337884, 13: 0.9111111111111111, 14: 0.9922480620155039, 15: 0.9662650602
409638, 16: 0.9535398230088495, 17: 0.9771573604060914, 18: 0.9650205761316872, 19: 0.9838709677419355, 20: 0.96276595744680
85, 21: 1.0, 22: 0.96, 23: 0.978021978021978, 24: 0.9643765903307888}

spec : {0: 0.9862343224227592, 1: 0.9903451605117065, 2: 0.9855655466161856, 3: 0.9899411187438666, 4: 0.9425360474978796, 5
: 0.9939927054280198, 6: 0.9661544446605719, 7: 0.9630509939498704, 8: 0.9778054345571459, 9: 0.9750889679715302, 10: 0.9771
660264618011, 11: 0.9375, 12: 0.9468883032637341, 13: 0.9178725068439577, 14: 0.9875292283710054, 15: 0.9474921630094044, 16
: 0.954213538582988, 17: 0.9715121951219512, 18: 0.9543016093781045, 19: 0.9480825958702065, 20: 0.9647345713749765, 21: 0.9
776216016275199, 22: 0.9639029892837, 23: 0.9715974075486085, 24: 0.9719079204057745}

**Comment by af1tang** [comment]
@nasatony -- go to the `make_labels` method under `preprocessing.py` and have it return the variables `dx_freq` and `dx_dct`, which stand for "diagnostic frequency" and "diagnosis dictionary", respectively. 

I noticed you used `lstm-dx-x19-w2v` settings and got unreasonably high performance for diagnostic predictions. This is because word2vec features were built on the diagnostic summaries. Please see the paper for which auxiliary features are available for which task.
